#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-zsh
Version  : 0.3.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/d4/75/2e7ca5e0cff83cb3a9700a5323ed508edc4fbb93cd32c9566e28fb212e4c/colcon-zsh-0.3.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/d4/75/2e7ca5e0cff83cb3a9700a5323ed508edc4fbb93cd32c9566e28fb212e4c/colcon-zsh-0.3.1.tar.gz
Summary  : Extension for colcon to provide Z shell scripts.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-zsh-python3
Requires: colcon-zsh-python
BuildRequires : buildreq-distutils3

%description
==========

%package python
Summary: python components for the colcon-zsh package.
Group: Default
Requires: colcon-zsh-python3

%description python
python components for the colcon-zsh package.


%package python3
Summary: python3 components for the colcon-zsh package.
Group: Default
Requires: python3-core

%description python3
python3 components for the colcon-zsh package.


%prep
%setup -q -n colcon-zsh-0.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532981376
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
